# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               cvak's blog
tagline:             "Programming, DevOps, making stuff"
description:         'A stable place for longer posts not fitting reddit.'
url:                 https://github.com/cvakiitho/blog
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Tomas Hartmann
  url:               http://twitter.com/cvakiitho
  email:             hart@mann.cf

# Custom vars
version:             1.0.0
