# Dependencies
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :categories/:title/

# Setup
title:               Tomáš Hartmann's blog
tagline:             "Programming, DevOps, making stuff"
description:         'A stable place for longer posts.'
baseurl:             'https://blogmann.cz'
paginate:            3 

github:
  url:               https://github.com/cvakiitho/blog

# About/contact
author:
  name:              Tomáš Hartmann
  url:               http://twitter.com/cvakiitho
  email:             tomhartmann a_t email.cz

# Custom vars
version:             1.0.0
