# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Cvak's blog
tagline:             "Cvak's blog"
description:         'A stable place for longer posts not fitting reddit.'
url:                 https://blog.mann.cf
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tomas Hartmann
  url:               http://twitter.com/cvakiitho
  email:             hart@mann.cf

# Custom vars
version:             1.0.0
