# Dependencies
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :categories/:title/

# Setup
title:               cvak's blog
tagline:             "Programming, DevOps, making stuff"
description:         'A stable place for longer posts.'
baseurl:             'https://blogmann.cf'
paginate:            3 

github:
  url:               https://github.com/cvakiitho/blog

# About/contact
author:
  name:              Tomas Hartmann
  url:               http://twitter.com/cvakiitho
  email:             hart@mann.cf

# Custom vars
version:             1.0.0
